version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: blackhole_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  web:
    build: .
    container_name: blackhole_api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis

  worker:
    build: .
    container_name: blackhole_worker
    command: celery -A workers.celery_app worker --loglevel=info -c 4
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_gui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis_data: